language: go
services:
  - redis-server
env:
  - DEP_VERSION="0.3.2" REDIS_URL="localhost:6379"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure -vendor-only
go:
  - 1.8.x
  - 1.9.x
  - master
script:
  - go test -v ./...
