version: '3'

services:
  redis:
    image: redis:latest

  rubbernecker:
    image: golang:latest
    volumes:
      - .:/go/src/github.com/alphagov/paas-rubbernecker
    working_dir: /go/src/github.com/alphagov/paas-rubbernecker
    command: go run main.go
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis:6379
